.catalog:
  name: ink-api
  version: 0.1.1
  uuid: ink-api-1
  description: Ink api repo
  minimum_rancher_version: v1.2.0-pre4-rc1
  questions:
    - variable: POSTGRESQL_PASSWORD
      label: postgres db pass
      required: true
      type: password
      default: arandompassword
    - variable: SECRET_KEY_BASE
      label: secret key base
      required: true
      type: password
      default: 943d29212a265d6d7781b07f2850dde8b5b1bb72c2b713e2f72c74322d24f06a0da6276c8e88d454c976641fe410d9cc0fc4fd5ad7f2169dbb3593cc117e9d33
    - variable: SLANGER_APP_ID
      label: Slanger app id
      required: true
      type: string
      default: slangerappid
    - variable: SLANGER_HOST
      label: Slanger app id
      required: true
      type: string
      default: slangerappid
    - variable: SLANGER_PORT
      label: Slanger app id
      required: true
      type: string
      default: slangerappid
    - variable: SLANGER_KEY
      label: Slanger key
      required: true
      type: string
      default: slangerkey
    - variable: SLANGER_SECRET
      label: Slanger key
      required: true
      type: password
      default: 765ec374ae0a69f4ce44
    - variable: INK_PASSWORD
      label: Ink password
      required: true
      type: password
      default: abc12345
    - variable: INK_EMAIL
      label: Ink owner email
      required: true
      type: string
      default: admin@admin.com
    - variable: DEVISE_ADMIN_EMAIL
      label: Admin email
      required: true
      type: string
      default: admin@admin.com
    - variable: DEVISE_SECRET_KEY
      label: Devise secret key
      required: true
      type: password
      default: f89c3d1e35cd199ddd4b6d55318de7ce30c9451c27019394bab96a1acc90acb677578bc28
    - variable: RAILS_ENV
      label: Rails environment
      required: true
      type: enum
      default: production
      options:
        - production
        - development

version: '2'
services:
  ink:
    scale: 1
    start_on_create: true
  sidekiq:
    scale: 1
    start_on_create: true
  postgresql:
    scale: 1
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
